import { img, mirrorProducts, bedProducts } from "./images";

export type CategoryId =
  | "center-tables"
  | "tv-stands"
  | "mirrors"
  | "bed-frames"
  | "dressers";

export type Product = {
  id: string;
  name: string;
  category: CategoryId;
  price: number;
  stock: number;
  image: string;
  description: string;
  specs: { label: string; value: string }[];
  badge?: string;
};

export const categories: { id: CategoryId; label: string; image: string }[] = [
  { id: "center-tables", label: "Center Tables", image: img.centerTablesCategory },
  { id: "tv-stands", label: "TV Stands & Units", image: img.tvStandsCategory },
  { id: "mirrors", label: "Mirrors", image: img.mirrorsCategory },
  { id: "bed-frames", label: "Bed Frames", image: img.bedFramesCategory },
  { id: "dressers", label: "Dressers", image: img.dressersCategory },
];

export const categoryLabel = (id: CategoryId) =>
  categories.find((c) => c.id === id)?.label ?? id;

const spec = (a: string, b: string) => ({ label: a, value: b });

export const products: Product[] = [
  {
    id: "ct-01",
    name: "Marble-Top Center Table",
    category: "center-tables",
    price: 2800,
    stock: 4,
    image: img.marbleTable,
    description:
      "Honed marble top on a slim powder-coated steel frame. Built to anchor a living room without crowding it.",
    specs: [spec("Top", "Honed marble"), spec("Base", "Powder-coated steel"), spec("Size", "110 x 60 x 42 cm")],
    badge: "New",
  },
  {
    id: "ct-02",
    name: "Fluted Wood & Glass Table",
    category: "center-tables",
    price: 2400,
    stock: 6,
    image: img.glassTable,
    description:
      "Tempered glass over a fluted walnut body with an open lower shelf for books and remotes.",
    specs: [spec("Top", "10mm tempered glass"), spec("Body", "Fluted walnut"), spec("Size", "120 x 65 x 40 cm")],
    badge: "New",
  },
  {
    id: "ct-03",
    name: "Nesting Center Table Set (2pc)",
    category: "center-tables",
    price: 1600,
    stock: 6,
    image: img.marbleTable,
    description: "Two-piece nesting set that tucks away or spreads out for guests.",
    specs: [spec("Pieces", "2"), spec("Finish", "Matte lacquer"), spec("Size", "90 x 50 cm / 60 x 40 cm")],
  },
  {
    id: "ct-04",
    name: "Multi-Tier Storage Coffee Table",
    category: "center-tables",
    price: 2200,
    stock: 3,
    image: img.glassTable,
    description: "Two storage tiers and a lift-friendly top edge for everyday living rooms.",
    specs: [spec("Storage", "2 tiers"), spec("Finish", "Walnut veneer"), spec("Size", "120 x 60 x 45 cm")],
  },
  {
    id: "tv-01",
    name: "Fluted Floating TV Console",
    category: "tv-stands",
    price: 4200,
    stock: 2,
    image: img.tvStand,
    description:
      "Wall-hung fluted console with soft-close drawers and full cable management. Mounting included.",
    specs: [spec("Mount", "Wall-hung"), spec("Drawers", "4 soft-close"), spec("Length", "220 cm")],
    badge: "New",
  },
  {
    id: "tv-02",
    name: "LED Backlit Media Wall",
    category: "tv-stands",
    price: 6800,
    stock: 1,
    image: img.hero,
    description:
      "Full media wall with stone-look cladding, floating shelves and warm LED backlighting.",
    specs: [spec("Lighting", "Warm LED strip"), spec("Shelves", "3 floating"), spec("Build", "Custom to wall")],
    badge: "Custom Build",
  },
  {
    id: "tv-03",
    name: "Glossy Low TV Rack",
    category: "tv-stands",
    price: 3100,
    stock: 5,
    image: img.tvStand,
    description: "High-gloss low rack with a hidden compartment for decoders and consoles.",
    specs: [spec("Finish", "High gloss"), spec("Length", "180 cm"), spec("Cable", "Rear routing")],
  },
  {
    id: "tv-04",
    name: "Acoustic Panel Entertainment Wall",
    category: "tv-stands",
    price: 7400,
    stock: 1,
    image: img.hero,
    description: "Slatted acoustic panelling with an integrated console and concealed wiring.",
    specs: [spec("Panels", "Acoustic slat"), spec("Console", "Integrated"), spec("Build", "Custom to wall")],
  },
  {
    id: "mr-01",
    name: "Round Arch LED Mirror",
    category: "mirrors",
    price: 1650,
    stock: 3,
    image: mirrorProducts[0],
    description: "Oversized round mirror with a warm LED halo, set into a marble hallway wall.",
    specs: [spec("Frame", "Frameless, LED edge light"), spec("Shape", "Round"), spec("Diameter", "100 cm")],
    badge: "New",
  },
  {
    id: "mr-02",
    name: "Slatted Wood Console Mirror",
    category: "mirrors",
    price: 1350,
    stock: 5,
    image: mirrorProducts[1],
    description: "Full-length mirror set within a fluted wood panel wall, paired with a floating console.",
    specs: [spec("Frame", "Slim metal"), spec("Shape", "Rectangular"), spec("Size", "180 x 70 cm")],
  },
  {
    id: "mr-03",
    name: "LED Backlit Vanity Mirror",
    category: "mirrors",
    price: 1200,
    stock: 7,
    image: mirrorProducts[2],
    description: "Wall-mounted vanity mirror with a warm LED backlight strip and floating shelf below.",
    specs: [spec("Control", "Always-on LED"), spec("Light", "Warm backlight"), spec("Size", "80 x 120 cm")],
  },
  {
    id: "mr-04",
    name: "Organic Shape LED Mirror",
    category: "mirrors",
    price: 1550,
    stock: 2,
    image: mirrorProducts[3],
    description: "Asymmetric pebble-shaped mirror with a soft LED halo, mounted above a floating console.",
    specs: [spec("Shape", "Asymmetric"), spec("Light", "Halo LED"), spec("Size", "110 x 70 cm")],
    badge: "New",
  },
  {
    id: "mr-05",
    name: "Round Black-Frame Console Mirror",
    category: "mirrors",
    price: 1300,
    stock: 6,
    image: mirrorProducts[4],
    description: "Classic round mirror in a slim black frame, paired with a floating white console.",
    specs: [spec("Frame", "Slim black metal"), spec("Shape", "Round"), spec("Diameter", "80 cm")],
  },
  {
    id: "mr-06",
    name: "Gold-Lit Rounded Console Mirror",
    category: "mirrors",
    price: 1450,
    stock: 4,
    image: mirrorProducts[5],
    description: "Rounded-corner mirror with warm gold-toned edge lighting over a wood-and-white console.",
    specs: [spec("Frame", "Rounded, LED edge light"), spec("Shape", "Rectangular"), spec("Size", "90 x 130 cm")],
  },
  {
    id: "mr-07",
    name: "Tall Shelf-Side Wall Mirror",
    category: "mirrors",
    price: 1250,
    stock: 5,
    image: mirrorProducts[6],
    description: "Slim tall mirror in a black frame, mounted beside floating display shelves and a stone-top console.",
    specs: [spec("Frame", "Slim black metal"), spec("Shape", "Rectangular"), spec("Size", "60 x 160 cm")],
  },
  {
    id: "mr-08",
    name: "Round Mirror on Slatted Wall",
    category: "mirrors",
    price: 1500,
    stock: 3,
    image: mirrorProducts[7],
    description: "Large round mirror set into a dark slatted feature wall above a glossy black console.",
    specs: [spec("Frame", "Frameless"), spec("Shape", "Round"), spec("Diameter", "100 cm")],
  },
  {
    id: "mr-09",
    name: "Wall-Lit Round Console Mirror",
    category: "mirrors",
    price: 1400,
    stock: 4,
    image: mirrorProducts[8],
    description: "Round mirror with an integrated wall light, set above a slim wood console and pampas vase styling.",
    specs: [spec("Frame", "Slim metal"), spec("Shape", "Round"), spec("Diameter", "85 cm")],
  },
  {
    id: "mr-10",
    name: "Arched Backlit Console Mirror",
    category: "mirrors",
    price: 1600,
    stock: 3,
    image: mirrorProducts[9],
    description: "Tall arched mirror with warm perimeter backlighting over a floating stone-top console.",
    specs: [spec("Frame", "Backlit arch"), spec("Shape", "Arched"), spec("Size", "80 x 180 cm")],
    badge: "New",
  },
  {
    id: "bf-01",
    name: "Two-Tone Platform Bed with Pendant Lights",
    category: "bed-frames",
    price: 5200,
    stock: 2,
    image: bedProducts[0],
    description: "White and walnut platform bed with a matching side dresser and pendant lighting either side.",
    specs: [spec("Size", "King"), spec("Finish", "White & walnut"), spec("Extras", "Matching side dresser")],
    badge: "New",
  },
  {
    id: "bf-02",
    name: "Dark Panel Bed with Built-In Nightstands",
    category: "bed-frames",
    price: 6400,
    stock: 2,
    image: bedProducts[1],
    description: "Wide panelled headboard in walnut and charcoal with integrated bedside units.",
    specs: [spec("Size", "King"), spec("Finish", "Walnut & charcoal"), spec("Nightstands", "Built-in")],
  },
  {
    id: "bf-03",
    name: "Minimal White Platform Bed",
    category: "bed-frames",
    price: 5000,
    stock: 3,
    image: bedProducts[2],
    description: "Clean white platform bed with floating side tables, styled for a bright bedroom.",
    specs: [spec("Size", "Queen"), spec("Finish", "Matte white"), spec("Extras", "Floating nightstands")],
  },
  {
    id: "bf-04",
    name: "Floating Wood Bed with Under-Glow",
    category: "bed-frames",
    price: 5800,
    stock: 3,
    image: bedProducts[3],
    description: "Cantilevered walnut frame that reads as floating, with warm perimeter under-glow lighting.",
    specs: [spec("Size", "King"), spec("Lighting", "Perimeter LED"), spec("Base", "Concealed steel")],
  },
  {
    id: "bf-05",
    name: "White Platform Bed with Dresser Set",
    category: "bed-frames",
    price: 5500,
    stock: 2,
    image: bedProducts[4],
    description: "Bright white platform bed paired with a matching walnut dresser and pendant lights.",
    specs: [spec("Size", "King"), spec("Finish", "White & walnut"), spec("Set", "Includes matching dresser")],
    badge: "New",
  },
  {
    id: "bf-06",
    name: "Low-Profile Storage Bed Base",
    category: "bed-frames",
    price: 4600,
    stock: 4,
    image: bedProducts[5],
    description: "Grey wood-tone low platform base with matching open-shelf bedside units.",
    specs: [spec("Size", "King"), spec("Finish", "Grey wood-tone"), spec("Nightstands", "Open-shelf, included")],
  },
  {
    id: "bf-07",
    name: "Wood Slab Platform Bed",
    category: "bed-frames",
    price: 6100,
    stock: 2,
    image: bedProducts[6],
    description: "Solid wood platform bed with a full-width slab headboard against a dark feature wall.",
    specs: [spec("Size", "King"), spec("Headboard", "Full-width solid wood"), spec("Base", "Platform")],
  },
  {
    id: "bf-08",
    name: "Panel Headboard Bed with Art Nook",
    category: "bed-frames",
    price: 5900,
    stock: 2,
    image: bedProducts[7],
    description: "Two-tone panelled headboard bed styled with framed wall art and a black accent throw.",
    specs: [spec("Size", "King"), spec("Finish", "Walnut & white"), spec("Headboard", "Panelled")],
  },
  {
    id: "bf-09",
    name: "Low Platform Bed, Statement Wall Décor",
    category: "bed-frames",
    price: 4800,
    stock: 3,
    image: bedProducts[8],
    description: "Grey low-profile platform bed with a backlit headboard nook, styled for a statement bedroom.",
    specs: [spec("Size", "Queen"), spec("Finish", "Grey matte"), spec("Lighting", "Backlit headboard nook")],
  },
  {
    id: "bf-10",
    name: "Slatted Wood Headboard Bed",
    category: "bed-frames",
    price: 6600,
    stock: 1,
    image: bedProducts[9],
    description: "Floor-to-ceiling slatted wood headboard wall with pendant reading lights either side.",
    specs: [spec("Size", "King"), spec("Headboard", "Full-height slatted wood"), spec("Lighting", "Pendant, both sides")],
    badge: "Custom Build",
  },
  {
    id: "dr-01",
    name: "Six-Drawer Modern Dresser",
    category: "dressers",
    price: 3400,
    stock: 4,
    image: img.dresser,
    description: "Handleless six-drawer dresser with a routed grip channel.",
    specs: [spec("Drawers", "6"), spec("Finish", "Matte white"), spec("Size", "140 x 45 x 80 cm")],
    badge: "New",
  },
  {
    id: "dr-02",
    name: "Vanity Desk with Mirror",
    category: "dressers",
    price: 2900,
    stock: 3,
    image: img.dresser,
    description: "Vanity desk paired with a lit mirror and a soft-close drawer bank.",
    specs: [spec("Drawers", "3"), spec("Mirror", "LED lit"), spec("Size", "120 x 45 cm")],
  },
  {
    id: "dr-03",
    name: "Chest of Drawers (4pc)",
    category: "dressers",
    price: 2300,
    stock: 5,
    image: img.dresser,
    description: "Compact four-drawer chest for tight bedroom corners.",
    specs: [spec("Drawers", "4"), spec("Finish", "Oak veneer"), spec("Size", "80 x 45 x 100 cm")],
  },
  {
    id: "dr-04",
    name: "Entryway Console Table",
    category: "dressers",
    price: 1900,
    stock: 6,
    image: img.glassTable,
    description: "Slim entryway console with a shelf for baskets and keys.",
    specs: [spec("Shelf", "1 open"), spec("Finish", "Walnut"), spec("Size", "120 x 35 x 80 cm")],
  },
];

export const cedis = (n: number) => `GH\u20B5${n.toLocaleString()}`;

export const BUSINESS = {
  name: "Stelike Exclusives",
  phone: "+233 53 199 3984",
  whatsapp: "233531993984",
  instagram: ["@stelikexclusives", "@stelike_exclusives"],
  facebook: "Stelike Exclusives",
  city: "Accra, Ghana",
  coords: { lat: 5.6205, lng: -0.2295 },
  areas: "Accra, Achimota, East Legon, Kumasi, Takoradi",
};
